version: '2'
services:
    yolo-app:
        image: yolo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://yolo-mysql:3306/yolo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=yolo-elasticsearch:9300
        ports:
            - 8080:8080
    yolo-mysql:
        extends:
            file: mysql.yml
            service: yolo-mysql
    yolo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: yolo-elasticsearch
